.PHONY: ci start start-prod build lint lint-eslint lint-tsc lint-md lint-dup \
        lint-metrics lint-deps format ci-test-unit-client ci-test-unit-server \
        ci-test-integration test-e2e test-visual test-mutation \
        merge-mutation-reports test-load test-memory-leak lighthouse-desktop \
        lighthouse-mobile storybook-build pr-comments

ci:
	@echo stub ci
start:
	@echo stub start
start-prod:
	@echo stub start-prod
build:
	@echo stub build
lint:
	@echo stub lint
lint-eslint:
	@echo stub lint-eslint
lint-tsc:
	@echo stub lint-tsc
lint-md:
	@echo stub lint-md
lint-dup:
	@echo stub lint-dup
lint-metrics:
	@echo stub lint-metrics
lint-deps:
	@echo stub lint-deps
format:
	@echo stub format
ci-test-unit-client:
	@echo stub ci-test-unit-client
ci-test-unit-server:
	@echo stub ci-test-unit-server
ci-test-integration:
	@echo stub ci-test-integration
test-e2e:
	@echo stub test-e2e
test-visual:
	@echo stub test-visual
test-mutation:
	@echo stub test-mutation
merge-mutation-reports:
	@echo stub merge-mutation-reports
test-load:
	@echo stub test-load
test-memory-leak:
	@echo stub test-memory-leak
lighthouse-desktop:
	@echo stub lighthouse-desktop
lighthouse-mobile:
	@echo stub lighthouse-mobile
storybook-build:
	@echo stub storybook-build
pr-comments:
	@echo stub pr-comments
