.PHONY: ci start tests e2e-tests psalm deptrac phpinsights infection load-tests

ci:
	@echo stub ci
start:
	@echo stub start
tests:
	@echo stub tests
e2e-tests:
	@echo stub e2e-tests
psalm:
	@echo stub psalm
deptrac:
	@echo stub deptrac
phpinsights:
	@echo stub phpinsights
infection:
	@echo stub infection
load-tests:
	@echo stub load-tests
